#!/usr/bin/python3

import unittest
from my_module import MyClass

class TestMyClass(unittest.TestCase):
    def test_method1(self):
        # Test method 1 of MyClass
        obj = MyClass()
        result = obj.method1()
        self.assertEqual(result, expected_result)

    def test_method2(self):
        # Test method 2 of MyClass
        obj = MyClass()
        result = obj.method2()
        self.assertEqual(result, expected_result)

if __name__ == '__main__':
    unittest.main()
